os: linux
language: python
python:
- '3.6'
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
#install:
#  - pip install -q requests docker
before_script:
- make docker-login
script:
#- make build-ss
- make build-v2fly
#- make push-v2ray
- make build-net
- make push-net
after_script:
- docker images
- docker logout
env:
  global:
    secure: VuEGcw/IgWyW/LRHaKbnMLapiZlakzBSUlIo+rkNkJZ0Vj2y9LhfFTRJ3zXiRMEFQLDsQOKWQVnGn8m+W3GgiDBUjw9BfV4F3tJ3zj8GyufRgf6Jj1OmDTD2ADRlSQWLARpYLfio/LHFbICO+5eCQUxvvUvXTqSaluln62IWKXefEL6rrmHQJ6xM5DOSO4aBjO/Z+7h74vjVHHsaPl/XwHmjrMVWxtuka7vBAMPBXdWUBNJohVy0Pskq0yDv7ZZtcKfXdXMqBLlRf/eShcxZXW1+KIwLQYnTuovNu2W6X2l5L8U9EYsWp18bdfPmJDg9lq1qHI+JXuLZ5nLdQLQrbByshZsOB7OgIjIsftbcctVN0XxhGkzDmsfEf993xesLPs54dQ7gAR2ZXIrCOj2tyFfsurYmdzbpSImCz3TsTT3ckO3TrzWbU30YUUBXFNNsBhXg4ZU7t23zxB1ZOm7kzRq0Y93hM6dtW0hOUqI13q+i30BPhR9IyehWOlkQSR9brbA8xbicbnIyhM81SwH8TCQtM/CMsCUD7QCUbI7bGQdvkOji1LWQ32jvDidA2wR2q34AFHY6eyaMxPe0Xs3vxPh/9FO7LG2w6TRvEi+3s5EMOt0hO+z3yb24cbKXXJQBAlRxLvO7k29rPauk0ISczpEijflyB5zsaU1dVSxn8+8=
