##    Global settings
server_names = [
    "cloudflare-security",
    "google",
    "quad9-dnscrypt-ip4-filter-ecs-pri",
    "quad9-doh-ip4-port443-filter-ecs-pri",
]

listen_addresses = ['0.0.0.0:53']

## Maximum number of simultaneous client connections to accept
max_clients = 200
user_name = 'nobody'

## Require servers (from static + remote sources) to satisfy specific properties
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true

## Require servers defined by remote sources to satisfy specific properties
require_dnssec = true
require_nolog = true
require_nofilter = false
disabled_server_names = []
force_tcp = false
timeout = 3000
keepalive = 30

## Add EDNS-client-subnet information to outgoing queries
#edns_client_subnet = [
#    # GZ
#    "14.119.113.22/32",
#    "139.159.208.89/32",
#    # HK
#    "119.28.80.58/32",
#    "159.138.16.98/32",
#    # US: FL;NJ;LA
#    "199.181.140.27/32",
#    "23.73.237.27/32",
#    "108.61.219.200/32"
#]

## Response for blocked queries. Options are `refused`, `hinfo` (default) or
## an IP response. To give an IP response, use the format `a:<IPv4>,aaaa:<IPv6>`.
## Using the `hinfo` option means that some responses will be lies.
## Unfortunately, the `hinfo` option appears to be required for Android 8+
blocked_query_response = 'refused'

## Load-balancing strategy: 'p2' (default), 'ph', 'p<n>', 'first' or 'random'
## Randomly choose 1 of the fastest 2, half, n, 1 or all live servers by latency.
## The response quality still depends on the server itself.
lb_strategy = 'p2'

## Set to `true` to constantly try to estimate the latency of all the resolvers
## and adjust the load-balancing parameters accordingly, or to `false` to disable.
## Default is `true` that makes 'p2' `lb_strategy` work well.
lb_estimator = true

# log_level = 0
# log_file = '/var/log/dnscrypt-proxy.log'
# log_file_latest = true
# use_syslog = true

## Delay, in minutes, after which certificates are reloaded
cert_refresh_delay = 300

## Fallback resolvers
bootstrap_resolvers = [
    '1.1.1.2:53',
    '9.9.9.11:53',
    '8.8.8.8:53'
]

## Always use the fallback resolver before the system DNS settings.
ignore_system_dns = true

## Maximum time (in seconds) to wait for network connectivity before
## initializing the proxy.
## Useful if the proxy is automatically started at boot, and network
## connectivity is not guaranteed to be immediately available.
## Use 0 to not test for connectivity at all (not recommended),
## and -1 to wait as much as possible.
netprobe_timeout = 30
netprobe_address = '1.1.1.1:5353'

## Automatic log files rotation
log_files_max_size = 3
log_files_max_age = 3
log_files_max_backups = 1

##    Filters
block_ipv6 = true
block_unqualified = true
block_undelegated = true
reject_ttl = 600

## Enable a DNS cache to reduce latency and outgoing traffic
cache = true
cache_size = 30000
cache_min_ttl = 3600
cache_max_ttl = 86400
cache_neg_min_ttl = 3600
cache_neg_max_ttl = 3600

## Log client queries to a file
[query_log]
file = '/var/log/dnscrypt-query.log'
format = 'tsv'
ignored_qtypes = ['DNSKEY', 'NS']

[nx_log]
file = '/var/log/dnscrypt-nx.log'
format = 'tsv'


#########################
#        Servers        #
#########################
[sources]
[sources.'public-resolvers']
urls = [
    'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md',
    'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md'
]
cache_file = 'rules/public-resolvers.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 72
prefix = ''

[sources.quad9-resolvers]
urls = [
    "https://quad9.net/dnscrypt/quad9-resolvers.md",
    "https://raw.githubusercontent.com/Quad9DNS/dnscrypt-settings/main/dnscrypt/quad9-resolvers.md"
]
minisign_key = "RWQBphd2+f6eiAqBsvDZEBXBGHQBJfeG6G+wJPPKxCZMoEQYpmoysKUN"
cache_file = "rules/quad9-resolvers.md"
refresh_delay = 72
prefix = "quad9-"

[sources.'relays']
urls = [
    'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md',
    'https://download.dnscrypt.info/resolvers-list/v3/relays.md'
]
cache_file = 'rules/relays.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 72
prefix = ''
